name: Update arXiv Subscriptions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
    
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install feedparser jinja2 arxiv openai
    - name: Run script
      run: python generate_page.py
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Preserve GITHUB_TOKEN for git commands

    - name: Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated commit"
        git push
